services:
  event-consumer:
    build: ./event-consumer
    ports:
      - "8000:8000"
    volumes:
      - ./event-consumer:/app
    restart: always
    environment:
      SERVICE_NAME: ${SERVICE_NAME}
      SERVICE_PASSWORD: ${SERVICE_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - db

  event-propagator:
    build: ./event-propagator
    ports:
      - "8001:8001"
    volumes:
      - ./event-propagator:/app
    restart: always
    environment:
      SERVICE_NAME: ${SERVICE_NAME}
      SERVICE_PASSWORD: ${SERVICE_PASSWORD}
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - event-consumer

  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
volumes:
  mysql-data: