services:
  message-receiver-api:
    build: ./message-receiver-api
    ports:
      - "8000:8000"
    volumes:
      - ./message-receiver-api:/app
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - db

  message-sender-api:
    build: ./message-sender-api
    ports:
      - "8001:8001"
    volumes:
      - ./message-sender-api:/app
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - message-receiver-api

  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 420420
      MYSQL_DATABASE: messages-db
      MYSQL_USER: database_user
      MYSQL_PASSWORD: database_user_password
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
volumes:
  mysql-data: