services:
  event-consumer:
    build: ./event-consumer
    ports:
      - "8000:8000"
    volumes:
      - ./event-consumer:/app
    restart: always
    env_file:
      - ${LOCAL_ENV:+.env}
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - db

  event-propagator:
    build: ./event-propagator
    ports:
      - "8001:8001"
    volumes:
      - ./event-propagator:/app
    restart: always
    env_file:
      - ${LOCAL_ENV:+.env}
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - event-consumer

  db:
    image: mysql:8.4
    restart: always
    env_file:
      - ${LOCAL_ENV:+.env}
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
volumes:
  mysql-data: