services:
  event-consumer:
    build: ./event-consumer
    ports:
      - "8000:8000"
    volumes:
      - ./event-consumer:/app
    restart: always
    environment:
      SERVICE_NAME: ${SERVICE_NAME}
      SERVICE_PASSWORD: ${SERVICE_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - db

  event-propagator:
    build:
      context: ./event-propagator
    ports:
      - "8001:8001"
    volumes:
      - ./event-propagator:/app
      # If data is placed out of event-propagator context we can use this line
      # - C:/path/to/absolute/data.json/location:/app/data/data.json
    restart: always
    environment:
      SERVICE_NAME: ${SERVICE_NAME}
      SERVICE_PASSWORD: ${SERVICE_PASSWORD}
      SCHEDULER_INTERVAL: ${SCHEDULER_INTERVAL}
      ENDPOINT_TO_POST: ${ENDPOINT_TO_POST}
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - event-consumer

  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
volumes:
  mysql-data: