---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and test-lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Run Containers
        run: |
          docker-compose up -d --build
      - name: Run Tests for message-receiver-api
        run: |
          docker-compose exec -T message-receiver-api pytest tests/
      - name: Run Tests for message-sender-api
        run: |
          docker-compose exec -T message-sender-api pytest tests/
      - name: Stop Containers
        if: always()
        run: |
          docker-compose down
